version: '3'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/app

  api:
    build: ./server
    env_file:
      - ./server/dev.env
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/db:/data/db

  mongo-seed:
    build: ./mongo-seed
    profiles:
      - seed
    restart: on-failure:5
    depends_on:
      - mongodb
    volumes:
      - ./mongo-seed/dump:/dump
